import { OWNER_NAME, AI_NAME } from "@/config";

export default function TermsPage() {
      return (
              <div className="max-w-3xl mx-auto px-6 py-12 text-sm text-gray-300 space-y-8">
                    <h1 className="text-2xl font-bold text-white">{AI_NAME} — Terms of Use & Disclaimer</h1>h1>
                    <p className="text-gray-400">Last updated: April 2026 &nbsp;|&nbsp; Created by {OWNER_NAME}</p>p>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">1. About This Service</h2>h2>
                            <p>
                                {AI_NAME} is an AI-powered career advisor designed to help students and recent graduates
                                      in business, computer science, statistics, and data science with resume writing, interview
                                      preparation, job search strategy, and professional development guidance. It was created and
                                      deployed by {OWNER_NAME} as an independent project. It is not affiliated with, endorsed by,
                                      or operated by any university, employer, or professional career counseling organization.
                            </p>p>
                    </section>section>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">2. AI-Generated Content</h2>h2>
                            <p>
                                      All responses provided by {AI_NAME} are generated by a large language model (GPT-4.1 via
                                      the OpenAI API) and may be inaccurate, incomplete, outdated, or not applicable to your
                                      specific situation. You should not rely solely on this tool for any important career,
                                      employment, or professional decision.
                            </p>p>
                            <p>
                                {AI_NAME} may search the web or a curated knowledge base to supplement its responses.
                                      Even so, information retrieved may be out of date or imprecise. Always verify important
                                      information through official sources.
                            </p>p>
                    </section>section>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">3. Not Professional Advice</h2>h2>
                            <p>
                                {AI_NAME} does not provide professional career counseling, legal advice, financial advice,
                                      psychological counseling, or any other regulated professional service. Nothing on this
                                      platform constitutes a professional-client relationship. For high-stakes decisions — such
                                      as negotiating a job offer, addressing workplace legal matters, or managing mental health
                                      related to career stress — please consult a qualified professional or your
                                      university&apos;s career center.
                            </p>p>
                    </section>section>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">4. Use at Your Own Risk</h2>h2>
                            <p>
                                      Your use of {AI_NAME} is entirely at your own risk. {OWNER_NAME} accepts no liability
                                      for any outcomes — including missed job opportunities, inaccurate resume advice, or
                                      interview performance — resulting from your use of this service. The service is provided
                                      &quot;as is&quot; without any warranty of accuracy, completeness, or fitness for a
                                      particular purpose.
                            </p>p>
                    </section>section>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">5. Privacy & Data</h2>h2>
                            <p>
                                {AI_NAME} does not store your conversations or collect personal data beyond what is
                                      necessary to process your request in real time. Do not share sensitive personal
                                      information such as Social Security numbers, financial account details, or private
                                      medical information in your messages. Any information you submit is processed by
                                      third-party APIs (OpenAI, Exa) subject to their respective privacy policies.
                            </p>p>
                    </section>section>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">6. Acceptable Use</h2>h2>
                            <p>
                                      You agree to use {AI_NAME} only for lawful, career-related purposes. You may not use
                                      this service to generate harmful, deceptive, harassing, or discriminatory content. Attempts
                                      to manipulate, jailbreak, or extract unintended behavior from the AI are prohibited.
                                {OWNER_NAME} reserves the right to shut down or restrict access to this service at any time.
                            </p>p>
                    </section>section>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">7. Financial Costs & Availability</h2>h2>
                            <p>
                                      Each interaction with {AI_NAME} may incur API usage costs. This service is maintained on
                                      a best-effort basis and may be unavailable or rate-limited at any time. There is no
                                      guarantee of continuous uptime or service availability.
                            </p>p>
                    </section>section>
              
                    <section className="space-y-2">
                            <h2 className="text-lg font-semibold text-white">8. Changes to These Terms</h2>h2>
                            <p>
                                      These terms may be updated at any time without notice. Continued use of {AI_NAME}
                                      constitutes acceptance of the current terms.
                            </p>p>
                    </section>section>
              
                    <p className="text-gray-500 pt-4 border-t border-gray-700">
                            For questions or concerns, contact the creator: {OWNER_NAME}. This service is an independent
                            student project and is not affiliated with any academic institution or employer.
                    </p>p>
              </div>div>
            );
}</div>
